### ISSUE TITLE
Feature request: 動画ループ時、ループの冒頭に戻ったときに冒頭に戻ったことが分かるアクションが欲しい

### ISSUE THREAD

**Issue by hyumanase** [eatplaynap/shadone#144]
## 提案・要望

動画ループ時、ループの冒頭に戻ったときに冒頭に戻ったことが分かるアクションがあれば嬉しいです。

一例としては、動画の枠に色がつくとかでしょうか。
<img width="1102" alt="screenshot 2022-09-15 15 45" src="https://user-images.githubusercontent.com/13963571/190340446-0cea6bb7-c08b-4684-87f7-e3794853eb24.png">

## 背景

自分の英語力の問題かもしれないのですが、1分動画×3周とかシャドーイングしていると、「あれ今冒頭に戻ったんだっけ？」というのがたまにあるので。

**Comment by eatplaynap** [comment]
@hyumanase 
Hi, thanks for your a feature request! I'm sorry I didn't mention this at anywhere, but next time you give comment on this project I'm very happy if you write in English🤗

And regards to the issue, I'm thinking as below.
- Remaining loop count ( the number inside 💬 ) already shows the action that the loop backs to the top.
- If I implement an action as you suggest(changing color of the flame of video), it can be annoying when loop for a short time period because it will be constantly flicking.

I appreciate your request a lot but from the reasons above, I'm not thinking this feature to be implemented for now.
Thank you for your understanding🙌
